apiVersion: v1
kind: Namespace
metadata:
  name: ca-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaleup-pending
  namespace: ca-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scaleup-pending
  template:
    metadata:
      labels:
        app: scaleup-pending
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.10
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"